spring.application.name=rantbuddy
server.port=8080
server.address=0.0.0.0

aws.accessKeyId=AKIA3IN3FZPKEJJTZGFM
aws.secretKey=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
aws.region=eu-west-1
aws.userpoolid=eu-west-1_4pMGiow5C
aws.clientid=po9r4lqfprgh9ik2d7hi2g3g2
aws.clientSecret=15hnfrpk8vabjkqre1gfaa1akc7fir7g42uuce0m41lkd12gi6uj

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true